local mods = require("modifiers")
local programs = require("programs")

-- Configure what these relate to in programs.lua
hl.bind(mods.mod .. " + Return", hl.dsp.exec_cmd(programs.terminal), { description = "Terminal" })
hl.bind(mods.mod .. " + B", hl.dsp.exec_cmd(programs.openBrowser), { description = "Browser" })
hl.bind(mods.mod .. " + " .. mods.mod2 .. " + B", hl.dsp.exec_cmd(programs.openBrowserDev), { description = "Browser (Dev)" })
hl.bind(mods.mod .. " + A", hl.dsp.exec_cmd(programs.openAudioControls), { description = "Audio Controls" })
hl.bind(mods.mod .. " + T", hl.dsp.exec_cmd(programs.openActivityMonitor), { description = "Activity Monitor" })
hl.bind(mods.mod .. " + M", hl.dsp.exec_cmd(programs.openMusic), { description = "Music Player" })
hl.bind(mods.mod .. " + " .. mods.mod2 .. " + M", hl.dsp.exec_cmd(programs.openAudioVisualiser), { description = "Audio Visualiser" })
hl.bind(mods.mod .. " + F", hl.dsp.exec_cmd(programs.openFileManagerTui), { description = "File Manager (TUI)" })
hl.bind(mods.mod .. " + " .. mods.mod2 .. " + F", hl.dsp.exec_cmd(programs.openFileManagerGui), { description = "File Manager (GUI)" })
hl.bind(mods.mod .. " + Space", hl.dsp.exec_cmd(programs.openMenu), { description = "Menu" })
hl.bind(mods.mod .. " + " .. mods.mod2 .. " + C", hl.dsp.exec_cmd(programs.openConfig), { description = "Hyprland Config" })
hl.bind(mods.mod .. " + E", hl.dsp.exec_cmd(programs.openEditor), { description = "Text Editor" })
hl.bind(mods.mod .. " + " .. mods.mod2 .. " + E", hl.dsp.exec_cmd("code"), { description = "Visual Studio Code" })
hl.bind(mods.mod .. " + backslash", hl.dsp.exec_cmd(programs.openPasswordManager), { description = "Password Manager" })
hl.bind(mods.mod .. " + C", hl.dsp.exec_cmd(programs.openColorPicker), { description = "Color Picker" })
